AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.11
      Environment:
        Variables:
          TABLE_NAME: ItemsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: ItemsTable
      Events:
        GetAllItems:
          Type: Api
          Properties:
            Path: /items
            Method: GET
        GetItemById:
          Type: Api
          Properties:
            Path: /items/{id}
            Method: GET
        CreateItem:
          Type: Api
          Properties:
            Path: /items
            Method: POST

  ItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ItemsTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
